MACRO(CREATE_SYMLINK_COMMAND SOURCE DESTINATION RESULT)
	#GET_FILENAME_COMPONENT(SOURCE_REAL ${SOURCE} REALPATH)
	#GET_FILENAME_COMPONENT(DESTINATION_REAL ${DESTINATION} REALPATH)

	IF("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
		STRING(REPLACE "/" "\\" SOURCE_CLEAN ${SOURCE})
		STRING(REPLACE "/" "\\" DESTINATION_CLEAN ${DESTINATION})
	ELSE()
		SET(SOURCE_CLEAN ${SOURCE})
		SET(DESTINATION_CLEAN ${DESTINATION})
	ENDIF()

	# Windows Vista or higher has NTSF symlinks
	IF("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
		IF(${CMAKE_SYSTEM_VERSION} VERSION_GREATER "5.9") # Vista or higher
			SET(${RESULT} if NOT EXIST "${DESTINATION_CLEAN}" ( mklink /D "${DESTINATION_CLEAN}" "${SOURCE_CLEAN}" ) )
		ELSE()
			SET(${RESULT} echo d | xcopy /E /Y /Q "${SOURCE_CLEAN}" "${DESTINATION_CLEAN}")
		ENDIF()
	ENDIF()

	# Unix based systems have symlinks
	IF(UNIX)
		SET(${RESULT} ln -s -f "${SOURCE_CLEAN}" "${DESTINATION_CLEAN}")
	ENDIF()

	# If all else fails, just assume they have the cp command
	IF(NOT UNIX AND NOT ${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
		SET(${RESULT} cp -r "${SOURCE_CLEAN}" "${DESTINATION_CLEAN}")
	ENDIF()
ENDMACRO()