FILE(GLOB MODULES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/Modules Modules/*)

FOREACH(MODULE ${MODULES})
    IF(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/Modules/${MODULE}/CMakeLists.txt)
        STRING(TOUPPER ${MODULE} MODULE_UPPER)
        DEFINE_CACHE(JATTA_MODULE_${MODULE_UPPER} ON BOOL "Enables the ${MODULE} module.")
        ADD_SUBDIRECTORY(Modules/${MODULE})
    ENDIF()
ENDFOREACH()