MACRO(DEFINE_CACHE NAME VALUE TYPE DESCRIPTION)
    IF(DEFINED ${NAME})
        SET(${NAME} ${${NAME}} CACHE ${TYPE} ${DESCRIPTION})
    ELSE()
        SET(${NAME} ${VALUE} CACHE ${TYPE} ${DESCRIPTION})
    ENDIF()
ENDMACRO()

DEFINE_CACHE(JATTA_BUILD_EXAMPLES ON BOOL "Builds the examples.")