#ifdef JATTA_DOXYGEN
/** @mainpage Jatta
 *
 *  @section intro Introduction
 *  Jatta is an object oriented General Utility Library.  Jatta simplifies the process of creating
 *  windows, working with OpenGL, networking, loading in images and models, and much more.
 *
 *  The library does not depend on OpenGL, and optionally it can be disabled when building Jatta.
 *  All tools included can be used in any project for any purpose, including commercial.  Please see
 *  the @ref license for more information.
 */

/** @page downloads Downloads
 *  While Jatta is in development we do not have binary releases and require that you build the
 *  library form source.  You can grab the source from Github: @n
 *  https://github.com/JoshuaBrookover/Jatta
 *
 *  You can grab the pre-built libraries that Jatta relies on below.
 *
 *  <b>Windows (Visual Studio) 32bit</b> @n
 *  COMING EVENTUALLY
 *
 *  <b>Windows (Visual Studio) @b 64bit</b> @n
 *  COMING (NOT SO) SOON
 *
 *  <b>MinGW 32bit</b> @n
 *  <a href="http://dl.dropbox.com/u/11093974/JattaLibs/mingw32_dep.zip">mingw32_dep.zip</a>
 *
 *  <b>MinGW 64bit</b> @n
 *  COMING (NOT SO) SOON
 *
 *  <b>Linux 32bit</b> @n
 *  COMING (NOT SO) SOON
 *
 *  <b>Linux 64bit</b> @n
 *  <a href="http://dl.dropbox.com/u/11093974/JattaLibs/linux64_dep.tar.gz">linux64_dep.tar.gz</a>
 *
 *  <b>MacOS 32bit</b> @n
 *  COMING EVENTUALLY
 *
 *  <b>MacOS 64bit</b> @n
 *  COMING SOON
 */

/** @page license License
 *  @section note Note
 *  If you plan to redistribute Jatta with your product (as a shared library or otherwise) then you
 *  must also include acknowledgements to the libraries Jatta relies on.  You can see all of those
 *  on the @ref acknowledgements page.  If you have customized your build to exclude certain
 *  libraries then you DO NOT have to include acknowledgements for the excluded libraries.  To be
 *  safe, you should rely on the acknowledgements file generated by Jatta on build.  You can find it
 *  in your build directory under the src directory or in the installation directory named
 *  "acknowledgements.txt"
 *
 *  You do not have to include the acknowledgements.txt file with your project, just make sure that
 *  this information is somewhere!  If your product has other documentation, or a readme, include
 *  it in there instead if you wish.
 *
 *  @section bsd License (BSD 2-Clause)
 *  Copyright (C) 2012-2013, Joshua Brookover, Amber Thrall and Westley Wood@n
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without modification, are permitted
 *  provided that the following conditions are met:
 *
 *  @li Redistributions of source code must retain the above copyright notice, this list of
 *  conditions and the following disclaimer.
 *  @li Redistributions in binary form must reproduce the above copyright notice, this list of
 *  conditions and the following disclaimer in the documentation and/or other materials provided
 *  with the distribution.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 *  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND 
 *  FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 *  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 *  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 */

/** @page acknowledgements Acknowledgements
 *  Jatta utilizes the following fantastic libraries.  This project would not be possible without
 *  them!
 *
 *  @b libpng http://www.libpng.org/ @n
 *  Copyright (C) 1998-2012, Glenn Randers-Pehrson@n
 *  Copyright (C) 1996-1997, Andreas Dilger@n
 *  Copyright (C) 1995-1996, Guy Eric Schalnat, Group 42, Inc.@n
 *
 *  @b zlib http://www.zlib.net/ @n
 *  Copyright (C) 1995-2012, Jean-loup Gailly and Mark Adler
 *
 *  @b The @b OpenGL @b Extension @b Wrangler @b Library http://glew.sourceforge.net/ @n
 *  Copyright (C) 2002-2007, Milan Ikits <milan ikits[]ieee org>@n
 *  Copyright (C) 2002-2007, Marcelo E. Magallon <mmagallo[]debian org>@n
 *  Copyright (C) 2002, Lev Povalahev@n
 *  All rights reserved.
 *
 *  @b libjpeg http://libjpeg.sourceforge.net/ @n
 *  Copyright (C) 1991-2012, Thomas G. Lane, Guido Vollbeding.
 *
 *  @b FreeType http://www.freetype.org/ @n
 *  Copyright (C) 1996-2002, David Turner, Robert Wilhelm, and Werner Lemberg
 *
 *  @b Open @b Asset @b Import @b Library http://assimp.sourceforge.net/ @n
 *  Copyright (C) 2006-2012 assimp team@n
 *  All rights reserved.
 *
 *  @b PortAudio @b Portable @b Real-Time @b Audio @b Library http://www.portaudio.com/ @n
 *  Copyright (C) 1999-2011 Ross Bencina, Phil Burk
 *
 *  @b PulseAudio @b Implementation @b for @b PortAudio
 *  https://github.com/bkgood/portaudio-pulseaudio @n
 *  Copyright (C) 2011 William 'Bill' Good
 *
 *  @n This HTML help page was generated by Doxygen.  Check it out!@n
 *  http://www.stack.nl/~dimitri/doxygen/
 */

/** @page graphics Graphics & Windows
 *  @tableofcontents
 *  In this tutorial we will be going over how to create a basic window and initiate an OpenGL
 *  graphics device.
 *  @section create_window Creating a Window
 *  Creating a window in Jatta is a very simple process.  The code to create a window will be
 *  demonstrated first, then we will talk about what is happening.
 *  @code
 *  #include <Jatta.h>
 *
 *  int main()
 *  {
 *      // Create and populate the window style
 *      Jatta::WindowStyle style;
 *      style.title = "My First Window";
 *      style.width = 640;
 *      style.height = 480;
 *      style.backgroundColor = Jatta::Color(255, 0, 0);
 *
 *      // Create the window
 *      Jatta::Window window;
 *      window.Create(style);
 *
 *      // Begin the update loop
 *      while (window.IsOpen())
 *      {
 *          Jatta::Window::Update();
 *      }
 *  }
 *  @endcode
 *  @subsection window_style Window Style
 *  When creating a window, a Window Style must be specified.  This defines some information about
 *  the window before it is created.  Refer to Jatta::WindowStyle for a complete list of
 *  attributes.
 *  @subsection subsection2 The second subsection
 *  More text.
*/
#endif