/*#undef _JATTA_HWND_SIZE
#undef _JATTA_HWND
#undef _JATTA_DWORD_SIZE
#undef _JATTA_DWORD
#undef _JATTA_PIXELFORMATDESCRIPTOR_SIZE
#undef _JATTA_PIXELFORMATDESCRIPTOR
#undef _JATTA_FT_FACE_SIZE
#undef _JATTA_FT_FACE*/