if(MINGW)
    set(System_TYPE          ${CMAKE_SYSTEM_NAME})
    set(System_TYPE_SIMPLE   ${CMAKE_SYSTEM_NAME})
    set(System_DISTRO        "MinGW")
    set(System_DISTRO_SIMPLE "MinGW")
else()
    set(System_TYPE          ${CMAKE_SYSTEM_NAME})
    set(System_TYPE_SIMPLE   ${CMAKE_SYSTEM_NAME})
    set(System_DISTRO        ${CMAKE_SYSTEM_NAME})
    set(System_DISTRO_SIMPLE ${CMAKE_SYSTEM_NAME})
endif()
string(TOLOWER ${System_TYPE_SIMPLE} System_TYPE_LOWER)
string(TOLOWER ${System_DISTRO_SIMPLE} System_DISTRO_LOWER)

math(EXPR System_BITNESS "${CMAKE_SIZEOF_VOID_P} * 8")
